export const DCHeroList = [
	'batman',
	'superman',
	'Robin',
	'loboa',
	'congorilla',
	'black manta',
	'beastboy',
	'brainiac',
	'atom',
	'animal man',
	'amazo',
	'booster gold',
	'catman',
	'blackbat',
	'blue beetle',
	'circe',
	'gorilla grodd',
	'firestorm',
	'Felix faust',
	'hawkman',
	'hawkgirl',
	'Martian manhunter',
	'metamorpho',
	'mr terriffic',
	'nightwing',
	'night runner',
	'power girl',
	'prometheus',
	'ras al ghul',
	'red tornado',
	'Solomon grundy',
	'the question',
	'zatnna',
	'wildcat',
	'flash cu',
	'flash dcu',
	'green lantern',
	'shasam',
	'doomsday',
	'darkseid',
	'joker',
	'supergirl',
	'wonder women',
	'Jonah hex',
	'steel',
	'bane',
	'Batgirl',
	'black lightning',
	'birds of prey',
	'Alfred',
	'bizarro',
	'black adam',
	'cyborg',
	'black canary',
	'cat women',
	'cyborg superman',
	'twoface',
	'greenarrow',
	'lex luthor',
	'Harley quinn',
	'deadshot',
	'panguin',
	'parallax',
	'sinistro',
	'poison ive',
	'mr freeze',
	'scarecrow',
	'james jordon',
	'Lois lane',
	'magog',
	'starfire',
	'blackfire',
	'batman with prep',
	'doomsday',
	'Solomon grande',
	'shasam',
	'black adam',
	'batman',
	'punguan',
	'black fire',
	'black lightning',
	'animal man',
	'booster gold',
	'killer frost',
	'two face',
	'catman',
	'power girl',
	'congorala',
	'lusafer',
	'Dr fate',
	'the riter'
];

export const MCUHeroList = [
	'Jane foster',
	'Heimndall',
	'Captain America',
	'Mysterio',
	'Proxima midnight',
	'Thor',
	'Green goblin',
	'Mantis',
	'Stan lee',
	'Riot',
	'Deadpool',
	'Abomination',
	'Sand man',
	'Spider venom',
	'Korg',
	'Ancient one',
	'Wasp',
	'Dr strange',
	'Falcon',
	'Vulture',
	'Hela',
	'Odin',
	'Dr doom',
	'Ned',
	'Star lord',
	'Yondu',
	'Lizard',
	'Groot',
	'Loki',
	'Grandmaster',
	'Tina',
	'Wolverine',
	'Ghost rider(horse)',
	'Surtur',
	'Pepper',
	'Black widow',
	'The thing',
	'Rocket the raccon',
	'Ekectro',
	'Erishem',
	'Moon Knight (Steven)',
	'Ultron',
	'Vision',
	'Kilmonger',
	'Spider man(tobey)',
	'Thanos',
	'Nick fury',
	'Megnito',
	'Okoye',
	'Ronan',
	'Appocalypse',
	'Vulkyre',
	'Pietro',
	'Haward stark',
	'Dormammu',
	'Dr octopus',
	'Kaecilius',
	'Iron monger',
	'Jin gray',
	'Gamora',
	'Black panther',
	'Ant man',
	'Ultron bot',
	'Maphisto',
	'Spider man(Andrew)',
	'Drax',
	'Nebula',
	'Silver surfer',
	'Grandmaster',
	'Agetha',
	'Hawkeye',
	'Sersi',
	'Hulk',
	'Spiderman',
	'Eson the searcher',
	'Carnage',
	'War machine',
	'Sabertooth',
	'Ceptain marvel',
	'Ikaris',
	'Winter soldier',
	'Gor',
	'Cate bishop',
	'Moon Knight (marc)',
	'Ghost rider',
	'Quick silver',
	'Wong',
	'Human torch',
	'Ebony maw',
	'Gallactus',
	'Makkari',
	'Gor the god butcher',
	'Scott',
	'Shuri',
	'Scarlet witch',
	'Professor X',
	'Iron man',
	'Venom',
	'Ego the living planet',
	'The collecter'
];

export const UFC = [
	'Israel Adesanya',
	'Yoel Romero',
	'Michael Bisping',
	'Anderson Silva',
	'Jon Jones',
	'Khabib Nurmagomedov',
	'Charles Oliveira',
	'Khamzat Chimaev',
	'Wanderlei Silva',
	'Bigfoot Silva',
	'Alistair Overeem',
	'Georges St-Pierre',
	'BJ Penn',
	'Chael Sonnen',
	'Royce Gracie',
	'Forrest Griffin',
	'Kimbo Slice',
	'Dan Severn',
	"Sean O'Malley",
	'Demetrious Johnson',
	'Alex Pereira',
	'Brock Lesnar',
	'Kamaru Usman',
	'Francis Ngannou',
	'Leon Edwards',
	'Robert Whittaker',
	'Conor McGregor',
	'Paddy Pimblett',
	'Aljamain Sterling',
	'Dustin Poirier',
	'Justin Gaethje',
	'Michael Chandler',
	'Tom Breese',
	'Henry Cejudo',
	'Erick Silva',
	'Edson Barboza',
	'Vitor Belfort',
	'Tito Ortiz',
	'Rampage Jackson',
	'Song Yadong',
	'Dooho Choi',
	'Cub Swanson',
	'Frankie Edgar',
	'Urijah Faber',
	'Dominick Cruz',
	'Nick Diaz',
	'Nate Diaz'
];
