export const DCHeroList = [
	'batman',
	'superman',
	'Robin',
	'loboa',
	'congorilla',
	'black manta',
	'beastboy',
	'brainiac',
	'atom',
	'animal man',
	'amazo',
	'booster gold',
	'catman',
	'blackbat',
	'blue beetle',
	'circe',
	'gorilla grodd',
	'firestorm',
	'Felix faust',
	'hawkman',
	'hawkgirl',
	'Martian manhunter',
	'metamorpho',
	'mr terriffic',
	'nightwing',
	'night runner',
	'power girl',
	'prometheus',
	'ras al ghul',
	'red tornado',
	'Solomon grundy',
	'the question',
	'zatnna',
	'wildcat',
	'flash cu',
	'flash dcu',
	'green lantern',
	'shasam',
	'doomsday',
	'darkseid',
	'joker',
	'supergirl',
	'wonder women',
	'Jonah hex',
	'steel',
	'bane',
	'Batgirl',
	'black lightning',
	'birds of prey',
	'Alfred',
	'bizarro',
	'black adam',
	'cyborg',
	'black canary',
	'cat women',
	'cyborg superman',
	'twoface',
	'greenarrow',
	'lex luthor',
	'Harley quinn',
	'deadshot',
	'panguin',
	'parallax',
	'sinistro',
	'poison ive',
	'mr freeze',
	'scarecrow',
	'james jordon',
	'Lois lane',
	'magog',
	'starfire',
	'blackfire',
	'batman with prep',
	'doomsday',
	'Solomon grande',
	'shasam',
	'black adam',
	'batman',
	'punguan',
	'black fire',
	'black lightning',
	'animal man',
	'booster gold',
	'killer frost',
	'two face',
	'catman',
	'power girl',
	'congorala',
	'lusafer',
	'Dr fate',
	'the riter'
];

export const MCUHeroList = [
	'Jane foster',
	'Heimndall',
	'Captain America',
	'Mysterio',
	'Proxima midnight',
	'Thor',
	'Green goblin',
	'Mantis',
	'Stan lee',
	'Riot',
	'Deadpool',
	'Abomination',
	'Sand man',
	'Spider venom',
	'Korg',
	'Ancient one',
	'Wasp',
	'Dr strange',
	'Falcon',
	'Vulture',
	'Hela',
	'Odin',
	'Dr doom',
	'Ned',
	'Star lord',
	'Yondu',
	'Lizard',
	'Groot',
	'Loki',
	'Grandmaster',
	'Tina',
	'Wolverine',
	'Ghost rider(horse)',
	'Surtur',
	'Pepper',
	'Black widow',
	'The thing',
	'Rocket the raccon',
	'Ekectro',
	'Erishem',
	'Moon Knight (Steven)',
	'Ultron',
	'Vision',
	'Kilmonger',
	'Spider man(tobey)',
	'Thanos',
	'Nick fury',
	'Megnito',
	'Okoye',
	'Ronan',
	'Appocalypse',
	'Vulkyre',
	'Pietro',
	'Haward stark',
	'Dormammu',
	'Dr octopus',
	'Kaecilius',
	'Iron monger',
	'Jin gray',
	'Gamora',
	'Black panther',
	'Ant man',
	'Ultron bot',
	'Maphisto',
	'Spider man(Andrew)',
	'Drax',
	'Nebula',
	'Silver surfer',
	'Grandmaster',
	'Agetha',
	'Hawkeye',
	'Sersi',
	'Hulk',
	'Spiderman',
	'Eson the searcher',
	'Carnage',
	'War machine',
	'Sabertooth',
	'Ceptain marvel',
	'Ikaris',
	'Winter soldier',
	'Gor',
	'Cate bishop',
	'Moon Knight (marc)',
	'Ghost rider',
	'Quick silver',
	'Wong',
	'Human torch',
	'Ebony maw',
	'Gallactus',
	'Makkari',
	'Gor the god butcher',
	'Scott',
	'Shuri',
	'Scarlet witch',
	'Professor X',
	'Iron man',
	'Venom',
	'Ego the living planet',
	'The collecter'
];

export const UFC = [
	'Israel Adesanya',
	'Yoel Romero',
	'Michael Bisping',
	'Anderson Silva',
	'Jon Jones',
	'Khabib Nurmagomedov',
	'Charles Oliveira',
	'Khamzat Chimaev',
	'Wanderlei Silva',
	'Bigfoot Silva',
	'Alistair Overeem',
	'Georges St-Pierre',
	'BJ Penn',
	'Chael Sonnen',
	'Royce Gracie',
	'Forrest Griffin',
	'Kimbo Slice',
	'Dan Severn',
	"Sean O'Malley",
	'Demetrious Johnson',
	'Alex Pereira',
	'Brock Lesnar',
	'Kamaru Usman',
	'Francis Ngannou',
	'Leon Edwards',
	'Robert Whittaker',
	'Conor McGregor',
	'Paddy Pimblett',
	'Aljamain Sterling',
	'Dustin Poirier',
	'Justin Gaethje',
	'Michael Chandler',
	'Tom Breese',
	'Henry Cejudo',
	'Erick Silva',
	'Edson Barboza',
	'Vitor Belfort',
	'Tito Ortiz',
	'Rampage Jackson',
	'Song Yadong',
	'Dooho Choi',
	'Cub Swanson',
	'Frankie Edgar',
	'Urijah Faber',
	'Dominick Cruz',
	'Nick Diaz',
	'Nate Diaz'
];

export const HP = [
	'Goyal',
	'Author weasley',
	'Neville longbottom',
	'Tonks',
	'Charlie weasley',
	'Fleur delector',
	'Ginny weasley',
	'Percy weasley',
	'Hagrid',
	'Hermione Granger',
	'Harry potter',
	'Molly weasley',
	'Tom riddel',
	'Dudley',
	'Aunt petunia',
	'The sorting hat',
	'Kingsley shacklbolt',
	'Poffeser quirrel',
	'Winky',
	'Hedwig',
	'Uncle Vernon',
	'Mcgonagal',
	'Proffesr umbridge',
	'Peter pettigrew',
	'Sybil treawnley',
	'Draco malfoy',
	'Proffeser flitwick',
	'Lily potter',
	'Nagini',
	'Fudge',
	'Charity burage',
	'Katie bell',
	'Horace slughorn',
	'Fernen greyback',
	'Dean Thomas',
	'Luna love good',
	'Cho chang',
	'Lavender brown',
	'Kercher',
	'Pansy Parkinson',
	'Mr olivander',
	'Fred weasley',
	'Snape',
	'Ron weasley',
	'Lavender brown',
	'Mad eye moody',
	'Peaves',
	'Jack slopper',
	'Victor Crum',
	'George weasley',
	'James potter',
	'Sirius black',
	'Oliver wood',
	'Belerix lestrange',
	'Lord Voldemort',
	'Remus',
	'Cedric diggory',
	'Crabb',
	'Dobby',
	'Dumbledore',
	'Bill weasley',
	'Poffeser binns',
	'Moaning myrtle'
];

export const SW = [
	'Kylo ren',
	'Rey palpatine',
	'Emperor palps',
	'Finn',
	'Obi wan',
	'General grevious',
	'Darth vader',
	'Darth maul',
	'Luke skywalker',
	'Boba fett',
	'Anakin skywalker',
	'Leia',
	'Lando',
	'Han solo',
	'Ahsoka',
	'Bossk',
	'Yoda',
	'Snoke',
	'Qui gon',
	'Padme',
	'Revan',
	'Jar jar binks',
	'Seventh sister',
	'2nd sister',
	'5th brother',
	'Lux',
	'C3po',
	'Ezra',
	'Kanan',
	'Sabine',
	'Hera',
	'Bb8',
	'Bb9e',
	'Chewbacca',
	'Chopper',
	'Ar2d2',
	'Count doo doo',
	'Darth plagues',
	'Thrawn',
	'Baby yoda',
	'The mando',
	'Cal kestis',
	'Trilla'
];

export const Disney = [
	'The Good Dinosaur',
	'Dinosaur',
	'Brother Bear 1&2',
	'Fantasia',
	'Raya And The Last Dragon',
	'Moana',
	'Lion King',
	'Hercules',
	'Brave',
	'The Sword In The Stone',
	'Mulan',
	'The Black Cauldron',
	'Aladdin',
	'Robin Hood',
	'Sleeping Beauty',
	'The Hunchback of Notre Dame',
	'The Emperors New Groove',
	'Snow White',
	'Pocahontas',
	'Beauty and the Beast',
	'Tangled',
	'Frozen 1&2',
	'A Christmas Carol',
	'Alice In Wonderland',
	'Cinderella',
	'Tarzan',
	'Pinocchio',
	'The Jungle Book',
	'The Little Mermaid',
	'Home Of The Range',
	'The Great Mouse Detective',
	'Peter Pan 1&2',
	'Ichabed and Mister Toad',
	'Lady and the Tramp',
	'Aristocrats',
	'Atlantis',
	'Princess and the Frog',
	'Winnie the Pooh',
	'Dumbo',
	'Bambi',
	'Encanto',
	'Luca',
	'Incredibles 1&2',
	'The Rescuers 1&2',
	'Fox and the Hound',
	'Oliver and Company',
	'Duck Tales',
	'The Nightmare Before Christmas',
	'Toy Story 1&2',
	'Toy Story 3&4',
	'Recess',
	'Lilo and Stitch',
	'Turning Red',
	'Teacher’s Pet',
	'Finding Nemo',
	'Finding Dory',
	'Chicken Little',
	'The Wild',
	'Meet The Robinsons',
	'Ratatouille',
	'Bolt',
	'UP',
	'Mars Needs Moms',
	'Wreck it Ralph+Ralph Breaks The Internet',
	'Coco',
	'Soul',
	'Big Hero 6',
	'Cars 1-3',
	'Planes',
	'Wall•E',
	'A Bug’s Life',
	'Treasure Planet',
	'Onward',
	'Monsters University+Monsters INC',
	'Inside Out'
];

export const Friends = [
	'Connor',
	'Abby',
	'Michael',
	'Cub',
	'Sally',
	'Naddy',
	'Ryan',
	'Andrea',
	'Madisyn',
	'Esteban',
	'Belvedere',
	'Genevieve',
	'Bob',
	'Unity',
	'Ross',
	'Yosef',
	'Lorelei',
	'DeMarcus',
	'Sherlyn',
	'Chad',
	'Ulysses',
	'Judith',
	'Monserrat',
	'Jason',
	'Emily',
	'Izzy',
	'Araceli',
	'Kiera',
	'Journey',
	'Mathias',
	'Patricia',
	'Ashley',
	'Morgana',
	'Rhys',
	'Rick',
	'Anneliese',
	'Hazel',
	'Willow',
	'Jay',
	'Nando'
];

export const BS = [
	'Shelly',
	'Nita',
	'Colt',
	'Bull',
	'Brock',
	'El Primo',
	'Barley',
	'Poco',
	'Rosa',
	'Jessie',
	'Dynamike',
	'Tick',
	'8-Bit',
	'Rico',
	'Darryl',
	'Penny',
	'Carl',
	'Jacky',
	'Gus',
	'Bo',
	'Emz',
	'Stu',
	'Piper',
	'Pam',
	'Frank',
	'Bibi',
	'Bea',
	'Nani',
	'Edgar',
	'Griff',
	'Grom',
	'Bonnie',
	'Hank',
	'Pearl',
	'Mandy',
	'Maisie',
	'Sam',
	'Lola',
	'Ash',
	'Belle',
	'Gale',
	'Colette',
	'Mortis',
	'Tara',
	'Gene',
	'Max',
	'Mr. P',
	'Sprout',
	'Byron',
	'Squeak',
	'Gray',
	'Willow',
	'Doug',
	'Chuck',
	'Lou',
	'Ruffs',
	'Buzz',
	'Fang',
	'Janet',
	'Otis',
	'R-T',
	'Charlie',
	'Eve',
	'Buster',
	'Spike',
	'Crow',
	'Leon',
	'Sandy',
	'Amber',
	'Meg',
	'Chester',
	'Surge',
	'Cordelius',
	'NewBrawler?'
];

export const Countries = ["Poland", "United States", "Thailand", "Russia", "Tanzania", "South Korea", "Ukraine", "Indonesia", "United Kingdom", "Uzbekistan", "Ghana", "Iran", "Mexico", "Morocco", "Angola", "Sudan", "Germany", "South Africa", "Italy", "Colombia", "Afghanistan", "DR Congo", "Phillippines", "Egypt", "Venezuela", "Ethiopia", "Vietnam", "France", "Myanmar", "Uganda", "Kenya", "Canada", "Algeria", "China", "Turkey", "Mozambique", "India", "Iraq", "Brazil", "Pakistan", "Bangladesh", "Spain", "Malaysia", "Nigeria", "Agentina", "Peru", "Japan", "Saudi Arabia", "Nepal", "Yemen", "Madagascar", "North Korea", "Côte d’lvoire", "Cameroon", "Australia", "Niger", "Sri lanka", "Burkina Faso", "Malawi", "Mali", "Romania", "Kazakhstan", "Syria", "Chile", "Zambia", "Guatemala", "Zimbabwe", "Netherlands", "Ecuador", "Senegal", "Cambodia", "Chad", "Somalia", "Guinea", "South Sudan", "Rwanda", "Benin", "Tunisia", "Burundi", "Belgium", "Cuba", "Bolivia", "Haiti", "Greece", "Dominican Republic", "Czechia", "Portugal", "Jordan", "Sweden", "Azerbaijan", "United Arab Emirates", "Hungary", "Honduras", "Belarus", "Tajikistan", "Austria", "Serbia", "Switzerland", "Papua New Guinea", "Israel", "Togo", "Sierra Leone", "Laos", "Bulgaria", "Paraguay", "Libya", "El Salvador", "Nicaragua", "Kyrgyzstan", "Lebanon", "Turkmenistan", "Singapore", "Denmark", "Finland"]